- name: install applications
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    state: present

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_os_family | lower }} {{ ansible_distribution_release | lower }} stable
    state: present

- name: install docker-ce
  apt:
    name: docker-ce

- name: download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: 0777

- name: Export DOCKER_HOST
  shell: echo $DOCKER_HOST
  environment:
    DOCKER_HOST: "tcp://127.0.0.1:8080"
